### ISSUE TITLE
DDS updates and improvements

### ISSUE THREAD

**Issue by bcdunbar** [plotly/dash-docs#144]
This is a follow-up to https://github.com/plotly/dash-docs/pull/136. I'll update the list after more reviews.

- [ ] add more Celery content to "Linking a Celery Process"
- [x] add more errors to "Common Errors" 
- [x] add contributing guide

If you have any more ideas that you would like to see in the DDS documentation discuss below.

**Comment by chriddyp** [comment]
- [ ] a static assets section. since the apps are deployed under a app name prefix, embedding `images` under `/assets/my-image.png` won't work, it has to be `'/{}/assets/my-image.png'.format(os.environ.get('DASH_APP', ''))`. We should test that on the actual instance and then recommend it
- [ ] We link to the CSS section in the docs, we should make sure that the current method of including CSS files through the `assets` folder works on DDS the same way

**Comment by chriddyp** [comment]
- [ ] Dash PDF Generation API

**Comment by chriddyp** [comment]
- [ ] Packaging private python packages for deployment

**Comment by chriddyp** [comment]
- [ ] For the Troubleshooting section, we should have a section about using the latest versions of packages with links to each package's changelogs.
- [ ] Related, if they are deploying _an existing app_, then they need the changes from dash 0.25.0 (https://github.com/plotly/dash/blob/master/CHANGELOG.md#0250---2018-08-14). The latest version of dash should be fine. If not, they might see this issue:
![image](https://user-images.githubusercontent.com/1280389/44479620-18776c00-a60f-11e8-8ce4-e316becbe3e8.png)

**Comment by bcdunbar** [comment]
@chriddyp starting to add some more content this week. If possible, can you point me towards some info and examples for https://github.com/plotly/dash-docs/issues/144#issuecomment-414877293
