### ISSUE TITLE
Improve readability

### ISSUE THREAD

**Issue by YunkeXiao** [plotly/dash-docs#401]
I think it would be useful to have a persistent table of contents on the User Guide/Component Libraries section of the Dash Docs. It would make navigating those sections a lot faster and efficient.

**Comment by byronz** [comment]
@cldougl  I wanna echo on this readability issue in a slightly different perspective. I also had this problem for my dash learning. but I found mostly on the plotly graph reference side, the dash doc itself looks fine for me. 

here below is very typical, I come accros the **layout** props `clickmode`, since layout has many props like most of the graphs, it has a long list, the indent visual line does help a little bit for the hierachy structure in case of short list, but it can be also confusing if it's long. 

![image](https://user-images.githubusercontent.com/1394467/52985681-f5adf080-33c2-11e9-8a9b-457a2ecceeac.png)

an improvement can be 
- increase the level of navigation TOC on the left
- a way to let user aware of the reading context, like I know the `clickmode` here is for layout, as normally I just search the term with browser search popup.

**Comment by chriddyp** [comment]
This has been done 🎉
