### ISSUE TITLE
dash-bio==0.1.2rc3 is still dependent on dash-0.40.0,and that cause  installation error

### ISSUE THREAD

**Issue by AlexLuya** [plotly/dash-docs#598]
Hello,requirements.txt lists this:
```
dash==1.0.1
dash-auth==1.2.0
dash-bio==0.1.2rc3
```
but dash-bio-0.1.2r3 or bio-0.1.2' requirements.txt lists this:
(https://github.com/plotly/dash-bio/blob/master/requirements.txt)
```
dash==0.40.0
dash-bio==0.1.2rc9
```
this conflict causes an installation error.

**Comment by chriddyp** [comment]
Thanks for reporting!Thanks for reporting! Investigating in https://github.com/plotly/dash-bio/pull/388

**Comment by mkcor** [comment]
@shammamah this issue isn't resolved yet because:

- [ ] we haven't updated the `dash-bio` package (incrementing the version number first and foremost) following https://github.com/plotly/dash-bio/pull/388;
- [ ] we haven't deployed this new version on PyPI (not sure whether it should be `0.1.3rc3` or `0.1.3rc4`, since I can see there's already a `0.1.3rc3` https://pypi.org/project/dash-bio/#history);
 - [ ] we haven't updated `dash-docs`'s `requirements.txt` accordingly.

So let's do the above.

I think it will not suffice though, because `pip` installs nested dependencies following the direct dependency's `requirements.txt`, not its `setup.py` (recalling https://github.com/plotly/dash-bio/issues/135#issuecomment-472037899, references therein and subsequent comments).

**Comment by mkcor** [comment]
Hi @AlexLuya,

You should now be able to run `pip install -r requirements.txt` smoothly.

Thanks again for reporting!
